server:
  port: 9191
  servlet:
    session:
       timeout: 300s
spring:   
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/e_prod_school_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: dev
    password: Dev123#@!
    platform: mysql
    initialization-mode: always
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update  
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: false